// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcLzIGBTmduwfbh3sBp13QzeKzFHB9nF0',
    appId: '1:190304445843:web:7b00c41c0800f2ba81f466',
    messagingSenderId: '190304445843',
    projectId: 'portland-me-charlotte-nc',
    authDomain: 'portland-me-charlotte-nc.firebaseapp.com',
    storageBucket: 'portland-me-charlotte-nc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RIJXvtJQEL8W1SMZOhurrOJf0_ge3rU',
    appId: '1:190304445843:android:edf2335a1ce2328281f466',
    messagingSenderId: '190304445843',
    projectId: 'portland-me-charlotte-nc',
    storageBucket: 'portland-me-charlotte-nc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOuxaLiEU2mPeGQsCP_qU8llkYdjoEtCA',
    appId: '1:190304445843:ios:993a49b5b37f899481f466',
    messagingSenderId: '190304445843',
    projectId: 'portland-me-charlotte-nc',
    storageBucket: 'portland-me-charlotte-nc.appspot.com',
    iosClientId: '190304445843-mc9ojhi125qbvaoponlpjaap5l6sci76.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
